apiVersion: batch/v1
kind: Job
metadata:
  name: thingspeak-demo
  namespace: default
  labels:
    job_name: thingspeak-demo
spec:
  template:
    metadata:
      labels:
        app: thingspeak-demo
      name: thingspeak-demo
    spec:
      containers:
        - image: "petrjamf/thingspeak-demo"
          imagePullPolicy: IfNotPresent
          name: "thingspeak-demo"
          env:
          - name: "API_KEY"
            valueFrom:
              secretKeyRef:
                name: thingspeak-api-key
                key: api_key
          - name: "CHANNEL_ID"
            valueFrom:
              secretKeyRef:
                name: thingspeak-channel-id
                key: channel_id
      restartPolicy: Never
